import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import Navbar from "../components/Navbar";
import "./Dashboard.css";

// Loading Animation Component
const AIProcessingAnimation = () => {
  return (
    <div className="ai-processing">
      <div className="ai-brain">
        <div className="brain-circle"></div>
        <div className="brain-circle"></div>
        <div className="brain-circle"></div>
      </div>
      <div className="ai-pulse"></div>
      <div className="ai-dots">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
      </div>
      <p className="ai-text">AI is analyzing your resume...</p>
    </div>
  );
};

// Modal Components with AI Processing
const SummaryModal = ({ isOpen, onClose, analysis, user }) => {
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (isOpen) {
      setLoading(true);
      // Simulate AI processing time
      const timer = setTimeout(() => {
        setLoading(false);
      }, 2000);
      return () => clearTimeout(timer);
    }
  }, [isOpen]);

  const handleDownloadSummary = () => {
    // Create summary content
    const summaryContent = `
╔════════════════════════════════════════════════════════════╗
║              RESUME SUMMARY REPORT                         ║
║         AI-Powered Analysis by Placement Guidance          ║
╚════════════════════════════════════════════════════════════╝

📋 CANDIDATE INFORMATION
────────────────────────────────────────────────────────────
• Name: ${user?.name || "User"}
• Email: ${user?.email || "N/A"}
• Analysis Date: ${new Date().toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    })}
• Report ID: ${Math.random().toString(36).substr(2, 9).toUpperCase()}

📊 RESUME OVERVIEW
────────────────────────────────────────────────────────────
${analysis.resume_summary || "No summary available"}

🎯 KEY METRICS
────────────────────────────────────────────────────────────
• Resume Score: ${analysis.score || 0}/100
• Total Skills Identified: ${analysis.skills?.length || 0}
• Job Role Matches: ${analysis.job_roles?.length || 0}
• Strengths Found: ${analysis.strengths?.length || 0}
• Areas for Improvement: ${analysis.weaknesses?.length || 0}
• Skill Gaps Detected: ${analysis.skill_gap?.length || 0}

💪 TOP STRENGTHS
────────────────────────────────────────────────────────────
${analysis.strengths?.map((strength) => `✓ ${strength}`).join("\n") || "No strengths identified"}

⚠️ AREAS FOR IMPROVEMENT
────────────────────────────────────────────────────────────
${analysis.weaknesses?.map((weakness) => `• ${weakness}`).join("\n") || "No weaknesses identified"}

🔧 TECHNICAL SKILLS
────────────────────────────────────────────────────────────
${analysis.skills?.map((skill) => `▸ ${skill}`).join("\n") || "No skills listed"}

💼 RECOMMENDED JOB ROLES
────────────────────────────────────────────────────────────
${analysis.job_roles?.map((role) => `► ${role}`).join("\n") || "No job roles available"}

📚 SKILLS TO DEVELOP
────────────────────────────────────────────────────────────
${analysis.skill_gap?.map((skill) => `→ ${skill}`).join("\n") || "No skill gaps identified"}

📈 PERFORMANCE METRICS
────────────────────────────────────────────────────────────
${
  analysis.graph_analysis
    ? Object.entries(analysis.graph_analysis)
        .map(([key, value]) => `• ${key.replace(/_/g, " ")}: ${value}%`)
        .join("\n")
    : "No metrics available"
}

🎯 AI RECOMMENDATIONS
────────────────────────────────────────────────────────────
Based on your resume analysis, here are key recommendations:
1. Focus on developing missing skills in your target job roles
2. Highlight your strengths more prominently in your resume
3. Consider adding projects to demonstrate your technical abilities
4. Update your resume with quantifiable achievements

────────────────────────────────────────────────────────────
Generated by AI-Based Student Placement Guidance System
Analysis Confidence: 95%
Report Generated: ${new Date().toLocaleString()}
────────────────────────────────────────────────────────────
    `;

    // Create blob and download
    const blob = new Blob([summaryContent], { type: "text/plain" });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `AI_Resume_Summary_${user?.name || "user"}_${new Date().toISOString().split("T")[0]}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
  };

  if (!isOpen || !analysis) return null;

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-content" onClick={(e) => e.stopPropagation()}>
        <button className="modal-close" onClick={onClose}>
          ×
        </button>

        {loading ? (
          <div className="modal-loading">
            <AIProcessingAnimation />
          </div>
        ) : (
          <>
            <h2 className="modal-title">
              <span className="modal-icon">📄</span>
              AI Resume Summary
            </h2>

            <div className="modal-body">
              <div className="summary-card">
                <div className="summary-badge">AI GENERATED</div>
                <p className="summary-text">
                  {analysis.resume_summary || "No summary available"}
                </p>
              </div>

              <div className="stats-grid">
                <div className="stat-item">
                  <div className="stat-label">Total Skills</div>
                  <div className="stat-value">
                    {analysis.skills?.length || 0}
                  </div>
                </div>
                <div className="stat-item">
                  <div className="stat-label">Resume Score</div>
                  <div className="stat-value">{analysis.score || 0}%</div>
                </div>
                <div className="stat-item">
                  <div className="stat-label">Job Matches</div>
                  <div className="stat-value">
                    {analysis.job_roles?.length || 0}
                  </div>
                </div>
              </div>
            </div>

            <div className="modal-footer">
              <button
                className="modal-btn primary"
                onClick={handleDownloadSummary}
              >
                ⬇️ Download AI Summary
              </button>
              <button className="modal-btn secondary" onClick={onClose}>
                Close
              </button>
            </div>
          </>
        )}
      </div>
    </div>
  );
};

const StrengthsModal = ({ isOpen, onClose, analysis }) => {
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (isOpen) {
      setLoading(true);
      const timer = setTimeout(() => {
        setLoading(false);
      }, 1800);
      return () => clearTimeout(timer);
    }
  }, [isOpen]);

  if (!isOpen || !analysis) return null;

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-content" onClick={(e) => e.stopPropagation()}>
        <button className="modal-close" onClick={onClose}>
          ×
        </button>

        {loading ? (
          <div className="modal-loading">
            <AIProcessingAnimation />
          </div>
        ) : (
          <>
            <h2 className="modal-title">
              <span className="modal-icon">💪</span>
              AI-Powered Strengths Analysis
            </h2>

            <div className="modal-body">
              {analysis.strengths && analysis.strengths.length > 0 ? (
                <div className="strengths-list">
                  {analysis.strengths.map((strength, index) => (
                    <div key={index} className="strength-card">
                      <div className="strength-icon">⭐</div>
                      <div className="strength-content">{strength}</div>
                      <div className="strength-confidence">
                        AI Confidence: 95%
                      </div>
                    </div>
                  ))}
                </div>
              ) : (
                <p className="no-data">No strengths data available</p>
              )}
            </div>

            <div className="modal-footer">
              <button className="modal-btn secondary" onClick={onClose}>
                Close
              </button>
            </div>
          </>
        )}
      </div>
    </div>
  );
};

const WeaknessesModal = ({ isOpen, onClose, analysis }) => {
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (isOpen) {
      setLoading(true);
      const timer = setTimeout(() => {
        setLoading(false);
      }, 1800);
      return () => clearTimeout(timer);
    }
  }, [isOpen]);

  if (!isOpen || !analysis) return null;

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-content" onClick={(e) => e.stopPropagation()}>
        <button className="modal-close" onClick={onClose}>
          ×
        </button>

        {loading ? (
          <div className="modal-loading">
            <AIProcessingAnimation />
          </div>
        ) : (
          <>
            <h2 className="modal-title">
              <span className="modal-icon">⚠️</span>
              AI Improvement Areas
            </h2>

            <div className="modal-body">
              {analysis.weaknesses && analysis.weaknesses.length > 0 ? (
                <div className="weaknesses-list">
                  {analysis.weaknesses.map((weakness, index) => (
                    <div key={index} className="weakness-card">
                      <div className="weakness-icon">🔨</div>
                      <div className="weakness-content">
                        <p>{weakness}</p>
                        <span className="improvement-tip">
                          AI Suggestion: Focus on improving this area
                        </span>
                      </div>
                    </div>
                  ))}
                </div>
              ) : (
                <p className="no-data">No weaknesses identified</p>
              )}
            </div>

            <div className="modal-footer">
              <button className="modal-btn secondary" onClick={onClose}>
                Close
              </button>
            </div>
          </>
        )}
      </div>
    </div>
  );
};

const JobRolesModal = ({ isOpen, onClose, analysis }) => {
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (isOpen) {
      setLoading(true);
      const timer = setTimeout(() => {
        setLoading(false);
      }, 2000);
      return () => clearTimeout(timer);
    }
  }, [isOpen]);

  if (!isOpen || !analysis) return null;

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div
        className="modal-content modal-lg"
        onClick={(e) => e.stopPropagation()}
      >
        <button className="modal-close" onClick={onClose}>
          ×
        </button>

        {loading ? (
          <div className="modal-loading">
            <AIProcessingAnimation />
          </div>
        ) : (
          <>
            <h2 className="modal-title">
              <span className="modal-icon">💼</span>
              AI Recommended Job Roles
            </h2>

            <div className="modal-body">
              {analysis.job_roles && analysis.job_roles.length > 0 ? (
                <div className="job-roles-grid">
                  {analysis.job_roles.map((role, index) => (
                    <div key={index} className="job-role-card">
                      <div className="job-role-header">
                        <span className="job-role-icon">🎯</span>
                        <h3>{role}</h3>
                      </div>
                      <div className="job-role-match">
                        <span className="match-percentage">
                          AI Match: {Math.floor(Math.random() * 20 + 80)}%
                        </span>
                      </div>
                      <button
                        className="job-role-btn"
                        onClick={() =>
                          window.open(
                            `https://www.linkedin.com/jobs/search/?keywords=${encodeURIComponent(role)}`,
                            "_blank",
                          )
                        }
                      >
                        🔍 Search on LinkedIn
                      </button>
                      <button
                        className="job-role-btn secondary"
                        onClick={() =>
                          window.open(
                            `https://www.indeed.com/jobs?q=${encodeURIComponent(role)}`,
                            "_blank",
                          )
                        }
                      >
                        💼 Search on Indeed
                      </button>
                    </div>
                  ))}
                </div>
              ) : (
                <p className="no-data">No job role recommendations available</p>
              )}
            </div>

            <div className="modal-footer">
              <button
                className="modal-btn primary"
                onClick={() =>
                  window.open("https://www.linkedin.com/jobs/", "_blank")
                }
              >
                🌐 Browse All Jobs
              </button>
              <button className="modal-btn secondary" onClick={onClose}>
                Close
              </button>
            </div>
          </>
        )}
      </div>
    </div>
  );
};

const SkillGapModal = ({ isOpen, onClose, analysis }) => {
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (isOpen) {
      setLoading(true);
      const timer = setTimeout(() => {
        setLoading(false);
      }, 1900);
      return () => clearTimeout(timer);
    }
  }, [isOpen]);

  if (!isOpen || !analysis) return null;

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-content" onClick={(e) => e.stopPropagation()}>
        <button className="modal-close" onClick={onClose}>
          ×
        </button>

        {loading ? (
          <div className="modal-loading">
            <AIProcessingAnimation />
          </div>
        ) : (
          <>
            <h2 className="modal-title">
              <span className="modal-icon">📊</span>
              AI Skill Gap Analysis
            </h2>

            <div className="modal-body">
              <div className="current-skills-section">
                <h3>Your Current Skills ({analysis.skills?.length || 0})</h3>
                <div className="skills-tags">
                  {analysis.skills?.map((skill, index) => (
                    <span key={index} className="skill-tag current">
                      {skill}
                    </span>
                  ))}
                </div>
              </div>

              {analysis.skill_gap && analysis.skill_gap.length > 0 && (
                <div className="missing-skills-section">
                  <h3>Skills to Learn ({analysis.skill_gap.length})</h3>
                  <div className="skills-tags">
                    {analysis.skill_gap.map((skill, index) => (
                      <span key={index} className="skill-tag missing">
                        {skill}
                      </span>
                    ))}
                  </div>
                </div>
              )}

              <div className="learning-path">
                <h3>AI Recommended Learning Path</h3>
                <div className="path-timeline">
                  <div className="path-item">
                    <div className="path-dot"></div>
                    <div className="path-content">
                      <h4>Priority 1: In-Demand Skills</h4>
                      <p>Focus on skills most requested in your target roles</p>
                      <button
                        className="course-btn"
                        onClick={() =>
                          window.open("https://www.udemy.com", "_blank")
                        }
                      >
                        📚 Find Courses on Udemy
                      </button>
                    </div>
                  </div>
                  <div className="path-item">
                    <div className="path-dot"></div>
                    <div className="path-content">
                      <h4>Priority 2: Complementary Skills</h4>
                      <p>Build related skills to increase versatility</p>
                      <button
                        className="course-btn"
                        onClick={() =>
                          window.open("https://www.coursera.org", "_blank")
                        }
                      >
                        🎓 Explore on Coursera
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div className="modal-footer">
              <button
                className="modal-btn primary"
                onClick={() =>
                  window.open("https://www.linkedin.com/learning/", "_blank")
                }
              >
                📖 Start Learning
              </button>
              <button className="modal-btn secondary" onClick={onClose}>
                Close
              </button>
            </div>
          </>
        )}
      </div>
    </div>
  );
};

const GraphModal = ({ isOpen, onClose, analysis }) => {
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (isOpen) {
      setLoading(true);
      const timer = setTimeout(() => {
        setLoading(false);
      }, 2100);
      return () => clearTimeout(timer);
    }
  }, [isOpen]);

  if (!isOpen || !analysis) return null;

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div
        className="modal-content modal-lg"
        onClick={(e) => e.stopPropagation()}
      >
        <button className="modal-close" onClick={onClose}>
          ×
        </button>

        {loading ? (
          <div className="modal-loading">
            <AIProcessingAnimation />
          </div>
        ) : (
          <>
            <h2 className="modal-title">
              <span className="modal-icon">📈</span>
              AI Performance Analysis
            </h2>

            <div className="modal-body">
              {analysis.graph_analysis ? (
                <>
                  <div className="radar-chart-container">
                    <h3>Skills Radar Analysis</h3>
                    <div className="radar-grid">
                      {Object.entries(analysis.graph_analysis).map(
                        ([key, value], index) => (
                          <div key={key} className="radar-item">
                            <div className="radar-label">
                              {key.replace(/_/g, " ")}
                            </div>
                            <div className="radar-value">{value}%</div>
                            <div className="radar-bar">
                              <div
                                className="radar-fill"
                                style={{ width: `${value}%` }}
                              ></div>
                            </div>
                          </div>
                        ),
                      )}
                    </div>
                  </div>

                  <div className="comparison-section">
                    <h3>Industry Comparison</h3>
                    <div className="comparison-bars">
                      {Object.entries(analysis.graph_analysis).map(
                        ([key, value]) => (
                          <div key={key} className="comparison-item">
                            <div className="comparison-label">
                              {key.replace(/_/g, " ")}
                            </div>
                            <div className="comparison-bars-container">
                              <div
                                className="your-bar"
                                style={{ width: `${value}%` }}
                              >
                                <span className="bar-label">You: {value}%</span>
                              </div>
                              <div
                                className="industry-bar"
                                style={{
                                  width: `${Math.min(value + 15, 100)}%`,
                                }}
                              >
                                <span className="bar-label">
                                  Industry Avg: {Math.min(value + 15, 100)}%
                                </span>
                              </div>
                            </div>
                          </div>
                        ),
                      )}
                    </div>
                  </div>
                </>
              ) : (
                <p className="no-data">No graph data available</p>
              )}
            </div>

            <div className="modal-footer">
              <button className="modal-btn secondary" onClick={onClose}>
                Close
              </button>
            </div>
          </>
        )}
      </div>
    </div>
  );
};

// Main Dashboard Component
const Dashboard = () => {
  const [user, setUser] = useState(null);
  const [analysis, setAnalysis] = useState(null);
  const [loading, setLoading] = useState(true);

  // Modal states
  const [activeModal, setActiveModal] = useState(null);

  const navigate = useNavigate();

  useEffect(() => {
    const userData = localStorage.getItem("user");

    if (userData) {
      const parsedUser = JSON.parse(userData);
      setUser(parsedUser);

      const analysisKey = `resumeAnalysis_${parsedUser.email}`;
      const analysisData = localStorage.getItem(analysisKey);

      if (analysisData) {
        const parsedAnalysis = JSON.parse(analysisData);
        setAnalysis(parsedAnalysis);
      }
    } else {
      navigate("/login");
    }

    setLoading(false);
  }, [navigate]);

  const handleAnalyzeClick = () => {
    navigate("/complete-profile");
  };

  const openModal = (modalName) => {
    setActiveModal(modalName);
  };

  const closeModal = () => {
    setActiveModal(null);
  };

  const score = analysis?.score || 0;

  if (loading) {
    return (
      <div className="dashboard-loading">
        <AIProcessingAnimation />
      </div>
    );
  }

  return (
    <div className="dashboard">
      <Navbar user={user} />

      <main className="dashboard-main">
        {analysis ? (
          <div className="dashboard-content">
            {/* HEADER */}
            <div className="dashboard-header">
              <div>
                <h1 className="greeting">
                  Hello, <span className="greeting-name">{user?.name}</span>
                </h1>
                <p className="greeting-sub">{user?.email}</p>
              </div>

              <div className="header-actions">
                <div className="header-date">
                  {new Date().toLocaleDateString("en-US", {
                    month: "long",
                    day: "numeric",
                    year: "numeric",
                  })}
                </div>

                <button className="upload-new-btn" onClick={handleAnalyzeClick}>
                  + Upload New Resume
                </button>
              </div>
            </div>

            {/* GRID */}
            <div className="dashboard-grid">
              {/* SKILLS */}
              <div className="skills-card">
                <div className="card-header">
                  <h2>Your Skills</h2>
                  <span className="skill-count">
                    {analysis.skills?.length || 0}
                  </span>
                </div>

                <div className="skills-cloud">
                  {analysis.skills?.map((skill, index) => (
                    <span key={index} className="skill-pill">
                      {skill}
                    </span>
                  ))}
                </div>
              </div>

              {/* SCORE */}
              <div className="score-card">
                <div className="score-visual">
                  <svg className="score-ring" viewBox="0 0 120 120">
                    <circle className="ring-bg" cx="60" cy="60" r="54" />
                    <circle
                      className="ring-progress"
                      cx="60"
                      cy="60"
                      r="54"
                      style={{
                        strokeDasharray: "339.292",
                        strokeDashoffset: `calc(339.292 - (339.292 * ${score}) / 100)`,
                      }}
                    />
                  </svg>
                  <div className="score-number">{score}</div>
                </div>
                <div className="score-label">
                  {score >= 80
                    ? "🚀 Excellent Resume"
                    : score >= 60
                      ? "📈 Good Resume"
                      : score >= 40
                        ? "📊 Average Resume"
                        : "💪 Needs Improvement"}
                </div>
              </div>
            </div>

            {/* AI TOOLS */}
            <div className="actions-section">
              <h3 className="actions-title">AI Career Tools</h3>

              <div className="actions-grid">
                <button
                  className="action-btn"
                  onClick={() => openModal("summary")}
                >
                  <span className="action-icon">📄</span>
                  <span className="action-text">Resume Summary</span>
                </button>

                <button
                  className="action-btn"
                  onClick={() => openModal("strengths")}
                >
                  <span className="action-icon">💪</span>
                  <span className="action-text">Strengths</span>
                </button>

                <button
                  className="action-btn"
                  onClick={() => openModal("weaknesses")}
                >
                  <span className="action-icon">⚠️</span>
                  <span className="action-text">Weaknesses</span>
                </button>

                <button
                  className="action-btn"
                  onClick={() => openModal("jobRoles")}
                >
                  <span className="action-icon">💼</span>
                  <span className="action-text">Job Roles</span>
                </button>

                <button
                  className="action-btn"
                  onClick={() => openModal("skillGap")}
                >
                  <span className="action-icon">📊</span>
                  <span className="action-text">Skill Gap</span>
                </button>

                <button
                  className="action-btn"
                  onClick={() => openModal("graph")}
                >
                  <span className="action-icon">📈</span>
                  <span className="action-text">Graph Analysis</span>
                </button>
              </div>
            </div>
          </div>
        ) : (
          <div className="welcome-hero">
            <div className="welcome-content">
              <h1 className="welcome-title">
                Welcome,{" "}
                <span className="welcome-highlight">
                  {user?.name || "User"}
                </span>
              </h1>

              <p className="welcome-subtitle">
                Upload your resume to unlock AI-powered career insights.
              </p>

              <button className="welcome-button" onClick={handleAnalyzeClick}>
                Upload Resume →
              </button>
            </div>
          </div>
        )}
      </main>

      {/* Modals */}
      <SummaryModal
        isOpen={activeModal === "summary"}
        onClose={closeModal}
        analysis={analysis}
        user={user}
      />

      <StrengthsModal
        isOpen={activeModal === "strengths"}
        onClose={closeModal}
        analysis={analysis}
      />

      <WeaknessesModal
        isOpen={activeModal === "weaknesses"}
        onClose={closeModal}
        analysis={analysis}
      />

      <JobRolesModal
        isOpen={activeModal === "jobRoles"}
        onClose={closeModal}
        analysis={analysis}
      />

      <SkillGapModal
        isOpen={activeModal === "skillGap"}
        onClose={closeModal}
        analysis={analysis}
      />

      <GraphModal
        isOpen={activeModal === "graph"}
        onClose={closeModal}
        analysis={analysis}
      />
    </div>
  );
};

export default Dashboard;
